### ISSUE TITLE
Multiple languages and preferred language

### ISSUE THREAD

**Issue by frodefi** [wix/gulp-json-angular-translate#1]
Great module, thanks!

A couple of questions:

First: Having multiple languages (and json files), gives the same number of angular config files, where each has it's own language as the preferred language. But in my case I have multiple languages that I want to preload (small app) and have one language as the preferred one. Would that be possible?

Second: What does the following line do in the resulting file:
`$translateProvider.translations(translations);`
What does that do? I may have missed this while reading the docs for angular-translate...

**Comment by nikaspran** [comment]
Hi - sorry for the delay, missed the issue notification!

Regarding #1, here's what you can do:
* Set `hasPreferredLanguage` to false so it doesn't add that to the result
* Concatenate whatever languages you want into one file using something like [grunt-contrib-concat](https://github.com/gruntjs/grunt-contrib-concat)
* Use `$translateProvider.preferredLanguage()` in your own app to set it what you want it to be :)

Regarding #2, that used to be the API for [angular-translate 1.x](https://github.com/angular-translate/angular-translate/wiki/Getting-Started#configuring-translateprovider); it doesn't do anything on the 2.x branch and is there only for backwards compatibility.
